version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - 4000:4000
    volumes:
      - ./api:/app
  client:
    build: ./client
    container_name: client_container
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
